name: CI - Calculadora

# Roda em qualquer push ou pull request, em qualquer branch
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes unitários
        run: pytest tests/test_calc.py

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test   # só roda se os testes unitários passarem
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t python-app .

      - name: Rodar testes de integração no Docker
        run: |
          if [ -f tests/test_integration.py ]; then
            docker run python-app pytest tests/test_integration.py
          else
            echo "Nenhum teste de integração definido, pulando etapa"
